# Generated by Django 6.0.4 on 2026-04-09 08:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('country', models.CharField(default='QA', max_length=50, verbose_name='الدولة')),
                ('language', models.CharField(choices=[('ar', 'عربي'), ('en', 'English')], default='ar', max_length=5, verbose_name='اللغة')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثّق')),
                ('daily_limit_minutes', models.PositiveIntegerField(default=30, verbose_name='الحد اليومي (دقائق)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'والد',
                'verbose_name_plural': 'أولياء الأمور',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(15)], verbose_name='العمر')),
                ('avatar_emoji', models.CharField(default='🧒', max_length=10, verbose_name='الأفاتار')),
                ('current_level', models.CharField(choices=[('L1', 'مبتدئ'), ('L2', 'متوسط'), ('L3', 'متقدم')], default='L1', max_length=2, verbose_name='المستوى الحالي')),
                ('total_stars', models.PositiveIntegerField(default=0, verbose_name='مجموع النجوم')),
                ('total_xp', models.PositiveIntegerField(default=0, verbose_name='مجموع النقاط')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='السلسلة الحالية')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='أطول سلسلة')),
                ('last_played', models.DateTimeField(blank=True, null=True, verbose_name='آخر لعب')),
                ('total_play_minutes', models.PositiveIntegerField(default=0, verbose_name='إجمالي وقت اللعب (دقائق)')),
                ('words_learned', models.PositiveIntegerField(default=0, verbose_name='الكلمات المتعلّمة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='الوالد')),
            ],
            options={
                'verbose_name': 'طفل',
                'verbose_name_plural': 'الأطفال',
                'ordering': ['-last_played'],
            },
        ),
    ]
