# Generated by Django 6.0.4 on 2026-04-09 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='المعرّف')),
                ('name_ar', models.CharField(max_length=50, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=50, verbose_name='الاسم بالإنجليزية')),
                ('emoji', models.CharField(max_length=10, verbose_name='الرمز')),
                ('color', models.CharField(default='#2EC4B6', max_length=7, verbose_name='اللون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_free', models.BooleanField(default=False, help_text='متاح في الإصدار المجاني', verbose_name='مجاني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('L1', 'مبتدئ — كلمات'), ('L2', 'متوسط — جمل'), ('L3', 'متقدم — جمل مركبة')], max_length=2, verbose_name='المستوى')),
                ('text_en', models.CharField(max_length=200, verbose_name='النص الإنجليزي')),
                ('text_ar', models.CharField(max_length=200, verbose_name='النص العربي')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='الرمز')),
                ('audio_en_url', models.URLField(blank=True, verbose_name='رابط الصوت الإنجليزي')),
                ('audio_ar_url', models.URLField(blank=True, verbose_name='رابط الصوت العربي')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'عنصر تعليمي',
                'verbose_name_plural': 'العناصر التعليمية',
                'ordering': ['category', 'level', 'order'],
                'unique_together': {('category', 'level', 'text_en')},
            },
        ),
    ]
