# Generated by Django 6.0.4 on 2026-04-09 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=2, verbose_name='المستوى')),
                ('game_mode', models.CharField(choices=[('quiz', 'اختبار'), ('match', 'توصيل'), ('spell', 'تهجئة'), ('listen', 'استمع')], max_length=10, verbose_name='نمط اللعب')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='النتيجة')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة')),
                ('stars_earned', models.PositiveIntegerField(default=0, verbose_name='النجوم المكتسبة')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='المدة (ثوانٍ)')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت اللعب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.category', verbose_name='الفئة')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.child', verbose_name='الطفل')),
            ],
            options={
                'verbose_name': 'جلسة لعب',
                'verbose_name_plural': 'جلسات اللعب',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('L1', 'مبتدئ'), ('L2', 'متوسط'), ('L3', 'متقدم')], max_length=2, verbose_name='المستوى')),
                ('stars', models.PositiveIntegerField(default=0, help_text='0-3', verbose_name='النجوم')),
                ('best_score', models.PositiveIntegerField(default=0, verbose_name='أفضل نتيجة')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='إجمالي الأسئلة')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ أول إكمال')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.category', verbose_name='الفئة')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='accounts.child', verbose_name='الطفل')),
            ],
            options={
                'verbose_name': 'تقدم فئة',
                'verbose_name_plural': 'تقدم الفئات',
                'unique_together': {('child', 'category', 'level')},
            },
        ),
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('minutes_played', models.PositiveIntegerField(default=0, verbose_name='الدقائق')),
                ('sessions_count', models.PositiveIntegerField(default=0, verbose_name='عدد الجلسات')),
                ('stars_earned', models.PositiveIntegerField(default=0, verbose_name='النجوم')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='accounts.child')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('child', 'date')},
            },
        ),
    ]
