# Generated by Django 6.0.4 on 2026-04-09 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الرمز')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='نسبة الخصم %')),
                ('discount_fixed_usd', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='خصم ثابت (USD)')),
                ('max_uses', models.PositiveIntegerField(default=100, verbose_name='أقصى استخدام')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='الاستخدام الحالي')),
                ('valid_from', models.DateTimeField(verbose_name='صالح من')),
                ('valid_until', models.DateTimeField(verbose_name='صالح حتى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'الكوبونات',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_ar', models.CharField(max_length=50, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=50, verbose_name='الاسم بالإنجليزية')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر (USD)')),
                ('price_qar', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر (QAR)')),
                ('interval', models.CharField(choices=[('monthly', 'شهري'), ('annual', 'سنوي'), ('lifetime', 'مدى الحياة')], max_length=10, verbose_name='الفترة')),
                ('max_children', models.PositiveIntegerField(default=4, verbose_name='أقصى عدد أطفال')),
                ('features', models.JSONField(default=list, help_text='["20 فئة","نطق صوتي",...]', verbose_name='المميزات')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Price ID')),
                ('tap_plan_id', models.CharField(blank=True, max_length=100, verbose_name='tap Plan ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_popular', models.BooleanField(default=False, verbose_name='الأكثر شيوعاً')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'خطة',
                'verbose_name_plural': 'الخطط',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'تجريبي'), ('active', 'نشط'), ('past_due', 'متأخر'), ('canceled', 'ملغي'), ('expired', 'منتهي')], default='trialing', max_length=10, verbose_name='الحالة')),
                ('gateway', models.CharField(choices=[('stripe', 'Stripe'), ('tap', 'tap'), ('manual', 'يدوي')], default='stripe', max_length=10, verbose_name='بوابة الدفع')),
                ('gateway_subscription_id', models.CharField(blank=True, max_length=200, verbose_name='معرّف الاشتراك الخارجي')),
                ('gateway_customer_id', models.CharField(blank=True, max_length=200, verbose_name='معرّف العميل الخارجي')),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='بداية الفترة الحالية')),
                ('current_period_end', models.DateTimeField(verbose_name='نهاية الفترة الحالية')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='نهاية الفترة التجريبية')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='الوالد')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.plan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='المبلغ (USD)')),
                ('amount_local', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='المبلغ (محلي)')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='العملة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('refunded', 'مسترد')], default='pending', max_length=10, verbose_name='الحالة')),
                ('gateway', models.CharField(default='stripe', max_length=10, verbose_name='البوابة')),
                ('gateway_payment_id', models.CharField(blank=True, max_length=200, verbose_name='معرّف الدفعة الخارجي')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='استجابة البوابة')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.subscription', verbose_name='الاشتراك')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
